name: DropperPlugin
author: disunion
main: com.disunion.dropper.DropperPlugin
version: 1.0
api-version: 1.8
commands:
  start:
    description: starts the game
    usage: /<command>
    permission: op
  endgame:
    description: stops the game
    usage: /<command>
    permission: op
  openGUI:
    description: Opens the GUI
    usage: /<command>
    permission: op
